name: Backend CI/CD Pipeline for Touristique

# Déclenche le workflow sur les push et pull requests vers la branche main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Définit les permissions pour le workflow
permissions:
  contents: read

jobs:
  # Job pour le backend (Spring Boot) - Build and Test
  backend-build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer Java (votre projet utilise Java 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Updated to Java 21
          distribution: 'temurin'

      # Étape 3 : Mettre en cache les dépendances Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Étape 4 : Compiler et exécuter les tests avec Maven
      - name: Build and test backend with Maven
        run: mvn clean install -B

      # Étape 5 : Publier les résultats des tests
      - name: Publish Backend Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Job pour déployer le backend (Docker Hub)
  backend-deploy:
    needs: backend-build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Updated to Java 21
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build JAR
        run: mvn package -DskipTests -B

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/touristique-backend:${{ github.sha }}